# .github/workflows/to_do.yml

name: CI for To-Do Application

on: 
  push:
    branches: 
      - master  
  pull_request:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' 

    - name: Print Python version
      run: python --version  # This helps to verify the Python environment

    - name: List files in repository
      run: ls -R  # This lists all files and directories to check their structure

    - name: Install dependencies
      run: python -m pip install --upgrade pip

    - name: Run tests
      run: python -m unittest discover -s tests
